Data augmentation utils
autonlab/autonbox pull request #4
Opened 2020-01-16 21:08 UTC by Jeanselme

Add two primitives for allowing a multi branch predictions in the data augmentation setting

2020-01-16 21:09 UTC, Jeanselme commented
I would need your help to check if they respect the core requirements

2020-01-21 18:25 UTC, d8w commented
May you add your primitive description to README.md?

2020-01-21 19:11 UTC, d8w requested changes
delete `from d3m.primitives.data_preprocessing.horizontal_concat import DSBOX`

2020-01-21 19:11 UTC, d8w commented on autonbox/merge_multipredictions.py
> +from d3m.primitives.data_preprocessing.horizontal_concat import DSBOX
To delete

2020-01-21 19:17 UTC, d8w requested changes

2020-01-21 19:17 UTC, d8w commented on autonbox/clean_augment.py
> +        'version': '0.1',
Use three part naming conversion for version: i.e. [Major].[Minor].[Patch]
`'version':'0.1.0'`

2020-01-21 19:17 UTC, d8w commented on autonbox/merge_multipredictions.py
> +        'version': '0.1',
Use three part naming conversion for version: i.e. [Major].[Minor].[Patch]
`'version':'0.1.0'`

2020-01-22 17:04 UTC, d8w approved these changes

2020-01-22 17:04 UTC, merged